(function(){
'use strict';
const MS_DAY=86400000;
const pad=n=>String(n).padStart(2,'0');
const parseDate=value=>{const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value||'');if(!m)return null;const y=+m[1],mo=+m[2],d=+m[3];if(y<1||mo<1||mo>12||d<1||d>daysInMonth(y,mo))return null;return{y,m:mo,d}};
const daysInMonth=(y,m)=>new Date(Date.UTC(y,m,0)).getUTCDate();
const serial=date=>Math.floor(Date.UTC(date.y,date.m-1,date.d)/MS_DAY);
const fromSerial=n=>{const d=new Date(n*MS_DAY);return{y:d.getUTCFullYear(),m:d.getUTCMonth()+1,d:d.getUTCDate()}};
const formatDate=d=>`${String(d.y).padStart(4,'0')}-${pad(d.m)}-${pad(d.d)}`;
const displayDate=d=>new Intl.DateTimeFormat('en-US',{weekday:'long',year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(d.y,d.m-1,d.d)));
const addDays=(date,n)=>fromSerial(serial(date)+n);
const addCalendar=(date,amount,unit)=>{if(unit==='days')return addDays(date,amount);if(unit==='weeks')return addDays(date,amount*7);let y=date.y,m=date.m;if(unit==='months'){const index=y*12+(m-1)+amount;y=Math.floor(index/12);m=((index%12)+12)%12+1}else y+=amount;return{y,m,d:Math.min(date.d,daysInMonth(y,m))}};
const dateDiff=(a,b,inclusive=false)=>{const raw=serial(b)-serial(a);return raw+(inclusive?(raw>=0?1:-1):0)};
const weekday=d=>new Date(serial(d)*MS_DAY).getUTCDay();
const isBusiness=d=>{const w=weekday(d);return w!==0&&w!==6};
const addBusiness=(date,count)=>{let d=date,left=Math.abs(count),step=count<0?-1:1;while(left){d=addDays(d,step);if(isBusiness(d))left--}return d};
const businessBetween=(a,b,inclusive=false)=>{let sign=serial(b)>=serial(a)?1:-1,total=0,cursor=inclusive?a:addDays(a,sign),end=serial(b);while(sign>0?serial(cursor)<=end:serial(cursor)>=end){if(isBusiness(cursor))total+=sign;cursor=addDays(cursor,sign)}return total};
const parseClock=value=>{const m=/^(\d{1,2}):(\d{2})$/.exec(value||'');if(!m||+m[1]>23||+m[2]>59)return null;return +m[1]*60 + +m[2]};
const elapsed=(start,end)=>{let n=end-start;if(n<0)n+=1440;return n};
const durationText=minutes=>{const sign=minutes<0?'−':'';const n=Math.abs(Math.round(minutes)),h=Math.floor(n/60),m=n%60;return `${sign}${h} ${h===1?'hour':'hours'}${m?` ${m} ${m===1?'minute':'minutes'}`:''}`};
const ageBetween=(birth,target)=>{if(serial(target)<serial(birth))return null;let years=target.y-birth.y,months=target.m-birth.m,days=target.d-birth.d;if(days<0){months--;const prevMonth=target.m===1?12:target.m-1,prevYear=target.m===1?target.y-1:target.y;days+=daysInMonth(prevYear,prevMonth)}if(months<0){years--;months+=12}const totalDays=dateDiff(birth,target);return{years,months,days,totalDays,totalWeeks:Math.floor(totalDays/7),totalMonths:years*12+months}};
const today=()=>{const n=new Date();return{y:n.getFullYear(),m:n.getMonth()+1,d:n.getDate()}};
const engine={parseDate,daysInMonth,serial,fromSerial,formatDate,displayDate,addDays,addCalendar,dateDiff,weekday,isBusiness,addBusiness,businessBetween,parseClock,elapsed,durationText,ageBetween,today};
if(typeof window!=='undefined')window.DateTimeEngine=engine;

const form=document.querySelector('[data-date-time-form]');if(!form)return;
const result=document.querySelector('[data-date-time-result]'),status=document.querySelector('[data-date-time-status]'),share=document.querySelector('[data-share]');
const set=(html,error=false)=>{status.textContent=error?html:'';status.dataset.error=error?'true':'false';result.innerHTML=error?'':html;result.hidden=error};
const value=name=>form.elements[name]?.value||'';
const number=name=>Number(value(name));
function calculate(update=true){try{const mode=form.dataset.mode;let html='';
 if(mode==='time'){const h=number('hours'),m=number('minutes'),s=number('seconds'),ah=number('adjustHours'),am=number('adjustMinutes'),as=number('adjustSeconds'),op=value('operation'),delta=(op==='subtract'?-1:1)*(ah*3600+am*60+as);if(![h,m,s,ah,am,as].every(Number.isFinite))throw Error('Enter valid hours, minutes, and seconds.');if(value('calculationType')==='clock'){const clock=parseClock(value('clock'));if(clock===null)throw Error('Enter a valid clock time.');const raw=clock*60+delta,day=Math.floor(raw/86400),normalized=((raw%86400)+86400)%86400,hour=Math.floor(normalized/3600),minute=Math.floor(normalized%3600/60),second=Math.floor(normalized%60),suffix=hour>=12?'PM':'AM',shown=hour%12||12;html=`<strong>${shown}:${pad(minute)}:${pad(second)} ${suffix}</strong><span>${day===0?'Same day':day>0?`${day} day${day===1?'':'s'} later`:`${Math.abs(day)} day${day===-1?'':'s'} earlier`}</span>`}else{const total=h*3600+m*60+s+delta,sign=total<0?'−':'',abs=Math.abs(Math.round(total));html=`<strong>${sign}${Math.floor(abs/3600)} hours, ${Math.floor(abs%3600/60)} minutes, ${abs%60} seconds</strong>`}}
 if(mode==='hours'||mode==='work'){const a=parseClock(value('start')),b=parseClock(value('end'));if(a===null||b===null)throw Error('Enter valid start and end times.');let mins=elapsed(a,b);if(mode==='work'){const br=number('break');if(!Number.isFinite(br)||br<0||br>mins)throw Error('Break time must be between zero and the elapsed shift length.');mins-=br}html=`<strong>${durationText(mins)}</strong><span>${(mins/60).toFixed(2)} decimal hours</span>`}
 if(mode==='timecard'){let total=0,rows=[];for(let i=0;i<7;i++){const a=parseClock(value(`start${i}`)),b=parseClock(value(`end${i}`)),br=number(`break${i}`)||0;if(a===null&&b===null)continue;if(a===null||b===null||br<0)throw Error('Complete both times for every used day.');const mins=elapsed(a,b)-br;if(mins<0)throw Error('A break cannot exceed its work period.');total+=mins;rows.push(`${form.elements[`start${i}`].dataset.day}: ${durationText(mins)}`)}html=`<strong>${durationText(total)}</strong><span>${(total/60).toFixed(2)} decimal hours</span><small>${rows.join(' · ')||'No work periods entered'}</small>`}
 if(mode==='date'){const d=parseDate(value('date')),amount=number('amount')*(value('operation')==='subtract'?-1:1);if(!d||!Number.isInteger(amount))throw Error('Enter a valid date and whole-number amount.');const out=addCalendar(d,amount,value('unit'));html=`<strong>${displayDate(out)}</strong><span>${formatDate(out)}</span>`}
 if(mode==='between'){const a=parseDate(value('startDate')),b=parseDate(value('endDate'));if(!a||!b)throw Error('Enter two valid dates.');const days=dateDiff(a,b,form.elements.inclusive.checked),abs=Math.abs(days);html=`<strong>${days} ${Math.abs(days)===1?'day':'days'}</strong><span>${Math.floor(abs/7)} weeks and ${abs%7} days</span>`}
 if(mode==='fromtoday'){const base=parseDate(value('base')),n=number('days')*(value('direction')==='ago'?-1:1);if(!base||!Number.isInteger(n))throw Error('Enter a valid base date and whole number of days.');const out=addDays(base,n);html=`<strong>${displayDate(out)}</strong><span>${formatDate(out)}</span>`}
 if(mode==='business'){const operation=value('operation'),a=parseDate(value('startDate'));if(!a)throw Error('Enter a valid start date.');if(operation==='between'){const b=parseDate(value('endDate'));if(!b)throw Error('Enter a valid end date.');const n=businessBetween(a,b,form.elements.inclusive.checked);html=`<strong>${n} business ${Math.abs(n)===1?'day':'days'}</strong>`}else{const n=number('days')*(operation==='subtract'?-1:1);if(!Number.isInteger(n))throw Error('Enter a whole number of business days.');const out=addBusiness(a,n);html=`<strong>${displayDate(out)}</strong><span>${formatDate(out)}</span>`}}
 if(mode==='age'){const birth=parseDate(value('birth')),target=parseDate(value('target'));if(!birth||!target)throw Error('Enter valid birth and target dates.');const age=ageBetween(birth,target);if(!age)throw Error('The target date cannot be before the birth date.');let next={y:target.y,m:birth.m,d:Math.min(birth.d,daysInMonth(target.y,birth.m))};if(serial(next)<serial(target))next={y:target.y+1,m:birth.m,d:Math.min(birth.d,daysInMonth(target.y+1,birth.m))};html=`<strong>${age.years} years, ${age.months} months, ${age.days} days</strong><span>${age.totalMonths} total months · ${age.totalWeeks} total weeks · ${age.totalDays} total days</span><small>Next birthday: ${displayDate(next)}</small>`}
 set(html);if(update){const url=new URL(location.href);url.search='';url.searchParams.set('state',btoa(JSON.stringify(Object.fromEntries(new FormData(form)))));history.replaceState(null,'',url)}return true
 }catch(e){set(e.message,true);return false}}
form.addEventListener('submit',e=>{e.preventDefault();calculate()});share?.addEventListener('click',async()=>{if(!location.search)return;try{await navigator.clipboard.writeText(location.href);share.textContent='Link copied'}catch{}});
function restore(){const raw=new URLSearchParams(location.search).get('state');if(!raw){if(form.dataset.mode==='fromtoday'){form.elements.base.value=formatDate(today())}if(form.dataset.mode==='age'){form.elements.target.value=formatDate(today())}return}try{const state=JSON.parse(atob(raw));for(const[k,v]of Object.entries(state))if(form.elements[k]){if(form.elements[k].type==='checkbox')form.elements[k].checked=v==='on';else form.elements[k].value=v}calculate(false)}catch{set('This shared calculator link contains invalid values. You can still enter new values.',true)}}restore();
})();
