const form=document.querySelector('[data-fraction-form]'),out=document.querySelector('[data-result]'),shareButton=document.querySelector('[data-share]');
const modes=['fraction-arithmetic','simplify-fraction','fraction-to-decimal','decimal-to-fraction','fraction-to-percentage','percentage-to-fraction'];
const fieldsByMode={'fraction-arithmetic':['operation','n1','d1','n2','d2'],'simplify-fraction':['n','d'],'fraction-to-decimal':['n','d'],'decimal-to-fraction':['decimal'],'fraction-to-percentage':['n','d'],'percentage-to-fraction':['percent']};
const gcd=(a,b)=>{a=Math.abs(Math.round(a));b=Math.abs(Math.round(b));while(b)[a,b]=[b,a%b];return a||1};
const fmt=n=>Number.isInteger(n)?String(n):Number(n.toFixed(8)).toString();
const reduce=(n,d)=>{if(d<0){n=-n;d=-d}const g=gcd(n,d);return[n/g,d/g]};
const currentMode=()=>form.dataset.mode==='all'?form.elements.mode.value:form.dataset.mode;
function render(title,value,steps){out.hidden=false;out.innerHTML='<p class="eyebrow">Result</p><h2>'+title+'</h2><div class="answer">'+value+'</div><p>'+steps+'</p>'}
function read(mode){const v={};for(const name of fieldsByMode[mode]||[]){const raw=form.elements[name]?.value;if(name==='operation'){if(!['add','subtract','multiply','divide'].includes(raw))return null;v[name]=raw;continue}if(typeof raw!=='string'||raw.trim()===''||!Number.isFinite(Number(raw)))return null;v[name]=Number(raw)}if(['fraction-arithmetic'].includes(mode)&&(v.d1===0||v.d2===0||(v.operation==='divide'&&v.n2===0)))return null;if(['simplify-fraction','fraction-to-decimal','fraction-to-percentage'].includes(mode)&&v.d===0)return null;return v}
function show(mode){document.querySelectorAll('[data-for]').forEach(x=>{x.hidden=!x.dataset.for.split(' ').includes(mode)})}
function stateUrl(mode){const u=new URL(location.href);u.search='';if(form.dataset.mode==='all')u.searchParams.set('mode',mode);for(const name of fieldsByMode[mode])u.searchParams.set(name,form.elements[name].value.trim());return u}
function calculate(event,update=true){event?.preventDefault();const mode=currentMode();if(!modes.includes(mode)){render('Check your values','—','Choose a supported calculation.');return false}const v=read(mode);if(!v){render('Check your values','—','Enter valid values. Denominators and divisors cannot be zero.');return false}
 if(mode==='fraction-arithmetic'){let n,d,symbol;if(v.operation==='add'){n=v.n1*v.d2+v.n2*v.d1;d=v.d1*v.d2;symbol='+'}else if(v.operation==='subtract'){n=v.n1*v.d2-v.n2*v.d1;d=v.d1*v.d2;symbol='−'}else if(v.operation==='multiply'){n=v.n1*v.n2;d=v.d1*v.d2;symbol='×'}else{n=v.n1*v.d2;d=v.d1*v.n2;symbol='÷'}const[nr,dr]=reduce(n,d);render('Fraction result',nr+'/'+dr,v.n1+'/'+v.d1+' '+symbol+' '+v.n2+'/'+v.d2+' = '+nr+'/'+dr+'.')}
 else if(mode==='simplify-fraction'){const[n,d]=reduce(v.n,v.d);render('Simplified fraction',n+'/'+d,'Divide the numerator and denominator by '+gcd(v.n,v.d)+'.')}
 else if(mode==='fraction-to-decimal'){render('Decimal',fmt(v.n/v.d),v.n+' ÷ '+v.d+' = '+fmt(v.n/v.d)+'.')}
 else if(mode==='decimal-to-fraction'){const scale=1000000,[n,d]=reduce(Math.round(v.decimal*scale),scale);render('Fraction',n+'/'+d,fmt(v.decimal)+' written as a fraction and reduced is '+n+'/'+d+'.')}
 else if(mode==='fraction-to-percentage'){const p=v.n/v.d*100;render('Percentage',fmt(p)+'%',v.n+' ÷ '+v.d+' × 100 = '+fmt(p)+'%.')}
 else{const scale=1000000,[n,d]=reduce(Math.round(v.percent*scale),100*scale);render('Fraction',n+'/'+d,fmt(v.percent)+'% = '+n+'/'+d+'.')}
 if(update)history.replaceState(null,'',stateUrl(mode));if(shareButton)shareButton.textContent='Share result';return true}
function restore(){if(!form||!location.search)return;const p=new URLSearchParams(location.search),mode=form.dataset.mode==='all'?p.get('mode'):form.dataset.mode;const has=form.dataset.mode==='all'?p.has('mode')||modes.some(m=>fieldsByMode[m].some(n=>p.has(n))):fieldsByMode[mode].some(n=>p.has(n));if(!has)return;if(!modes.includes(mode)||fieldsByMode[mode].some(n=>!p.has(n))){render('Check shared link','—','This shared calculator link is incomplete or unsupported.');return}for(const name of fieldsByMode[mode])form.elements[name].value=p.get(name);if(form.dataset.mode==='all')form.elements.mode.value=mode;show(mode);if(!read(mode)){render('Check shared link','—','This shared calculator link contains invalid values.');return}calculate(null,false)}
form?.addEventListener('submit',calculate);form?.querySelector('[name="mode"]')?.addEventListener('change',e=>show(e.target.value));shareButton?.addEventListener('click',async()=>{if(out?.hidden)return;try{if(navigator.share)await navigator.share({title:document.title,text:out.innerText.trim(),url:location.href});else{await navigator.clipboard.writeText(location.href);shareButton.textContent='Link copied'}}catch{}});restore();