import{format,percentageToRatio,ratioConversions,scaleRatio,simplifyRatio,solveProportion}from'./ratio-core.mjs';
const panels=[...document.querySelectorAll('[data-panel]')],tabs=[...document.querySelectorAll('[data-tab]')],result=document.querySelector('#result'),resultTitle=document.querySelector('#result-title'),resultValue=document.querySelector('#result-value'),resultDetail=document.querySelector('#result-detail'),share=document.querySelector('#share-result');
let current={mode:'simplify',title:'',value:'',detail:''};
const show=(title,value,detail,params={})=>{current={mode:document.querySelector('[data-tab][aria-selected="true"]').dataset.tab,title,value,detail};resultTitle.textContent=title;resultValue.textContent=value;resultDetail.textContent=detail;result.hidden=false;share.dataset.params=new URLSearchParams({mode:current.mode,...params}).toString();result.scrollIntoView({behavior:'smooth',block:'nearest'})};
const fail=message=>{resultTitle.textContent='Check your entries';resultValue.textContent='';resultDetail.textContent=message;result.hidden=false;share.dataset.params=''};
const activate=mode=>{tabs.forEach(tab=>tab.setAttribute('aria-selected',String(tab.dataset.tab===mode)));panels.forEach(panel=>panel.hidden=panel.dataset.panel!==mode);result.hidden=true;history.replaceState(null,'',location.pathname)};
tabs.forEach(tab=>tab.addEventListener('click',()=>activate(tab.dataset.tab)));
document.querySelector('#simplify-form').addEventListener('submit',event=>{event.preventDefault();try{const a=event.target.a.value,b=event.target.b.value,[x,y]=simplifyRatio(a,b);show('Simplified ratio',x+':'+y,a+':'+b+' reduces to '+x+':'+y+'.',{a,b})}catch(error){fail(error.message)}});
document.querySelector('#solve-form').addEventListener('submit',event=>{event.preventDefault();try{const fields=['a','b','c','d'],values=fields.map(name=>event.target[name].value.trim()),solved=solveProportion(values);event.target[fields[solved.index]].value=format(solved.answer);const final=fields.map(name=>event.target[name].value);show('Missing value',format(solved.answer),final[0]+':'+final[1]+' = '+final[2]+':'+final[3],Object.fromEntries(fields.map(name=>[name,event.target[name].value])))}catch(error){fail(error.message)}});
document.querySelector('#scale-form').addEventListener('submit',event=>{event.preventDefault();try{const a=event.target.a.value,b=event.target.b.value,target=event.target.target.value,[x,y]=scaleRatio(a,b,target);show('Scaled ratio',format(x)+':'+format(y),'The equivalent ratio keeps the same proportion.',{a,b,target})}catch(error){fail(error.message)}});
document.querySelector('#convert-form').addEventListener('submit',event=>{event.preventDefault();try{const a=event.target.a.value,b=event.target.b.value,data=ratioConversions(a,b);show('Ratio conversions',data.fraction,format(Number(a)/Number(b))+' as a decimal · '+format(data.percentage)+'%',{a,b})}catch(error){fail(error.message)}});
document.querySelector('#percentage-form').addEventListener('submit',event=>{event.preventDefault();try{const percent=event.target.percent.value,[a,b]=percentageToRatio(percent);show('Percentage as a ratio',a+':'+b,format(percent)+'% equals '+a+':'+b+'.',{percent})}catch(error){fail(error.message)}});
share.addEventListener('click',async()=>{const url=new URL(location.href);url.search=share.dataset.params;const data={title:current.title,text:current.value+(current.detail?' — '+current.detail:''),url:url.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.text+' '+data.url);share.textContent='Copied';setTimeout(()=>share.textContent='Share result',1800)}}catch(error){if(error.name!=='AbortError')share.textContent='Copy failed'}});
const query=new URLSearchParams(location.search),mode=query.get('mode');if(tabs.some(tab=>tab.dataset.tab===mode)){activate(mode);const form=document.querySelector('[data-panel="'+mode+'"] form');[...form.elements].forEach(input=>{if(input.name&&query.has(input.name))input.value=query.get(input.name)});form.requestSubmit()}
