import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import vm from'node:vm';
const source=await readFile('date-time.js','utf8'),window={};vm.runInNewContext(source,{window,document:{querySelector(){return null}},Date,Intl,Math,Number,String,RegExp});const e=window.DateTimeEngine;
assert.deepEqual({...e.parseDate('2028-02-29')},{y:2028,m:2,d:29});assert.equal(e.parseDate('2027-02-29'),null);assert.equal(e.parseDate('1900-02-29'),null);assert.ok(e.parseDate('2000-02-29'));
assert.equal(e.formatDate(e.addCalendar(e.parseDate('2028-01-31'),1,'months')),'2028-02-29');assert.equal(e.formatDate(e.addCalendar(e.parseDate('2027-01-31'),1,'months')),'2027-02-28');assert.equal(e.formatDate(e.addCalendar(e.parseDate('2028-02-29'),1,'years')),'2029-02-28');assert.equal(e.formatDate(e.addDays(e.parseDate('2027-12-31'),1)),'2028-01-01');
assert.equal(e.dateDiff(e.parseDate('2028-03-01'),e.parseDate('2028-03-31')),30);assert.equal(e.dateDiff(e.parseDate('2028-03-01'),e.parseDate('2028-03-31'),true),31);assert.equal(e.dateDiff(e.parseDate('2028-03-10'),e.parseDate('2028-03-01')),-9);
assert.equal(e.elapsed(e.parseClock('08:15'),e.parseClock('16:45')),510);assert.equal(e.elapsed(e.parseClock('22:00'),e.parseClock('02:00')),240);assert.equal(e.elapsed(e.parseClock('09:00'),e.parseClock('09:00')),0);assert.equal(e.durationText(90),'1 hour 30 minutes');
assert.equal(e.formatDate(e.addBusiness(e.parseDate('2028-01-07'),1)),'2028-01-10');assert.equal(e.businessBetween(e.parseDate('2028-01-03'),e.parseDate('2028-01-10')),5);assert.equal(e.businessBetween(e.parseDate('2028-01-03'),e.parseDate('2028-01-10'),true),6);
assert.deepEqual({...e.ageBetween(e.parseDate('2000-01-15'),e.parseDate('2025-03-20'))},{years:25,months:2,days:5,totalDays:9196,totalWeeks:1313,totalMonths:302});assert.equal(e.ageBetween(e.parseDate('2030-01-01'),e.parseDate('2029-01-01')),null);
for(const pair of [['2024-03-09','2024-03-11'],['2024-11-02','2024-11-04']])assert.equal(e.dateDiff(e.parseDate(pair[0]),e.parseDate(pair[1])),2,'date-only calculations stay stable across DST dates');
const slugs=['date-time-calculators','time-calculator','hours-calculator','work-hours-calculator','time-card-calculator','date-calculator','days-between-dates','days-from-today','business-days-calculator','age-calculator'],titles=new Set(),descriptions=new Set(),sitemap=await readFile('sitemap.xml','utf8');
for(const slug of slugs){const html=await readFile(`${slug}/index.html`,'utf8'),title=html.match(/<title>([^<]+)/)?.[1],description=html.match(/<meta name="description" content="([^"]+)/)?.[1];assert.ok(title&&description);assert.ok(!titles.has(title)&&!descriptions.has(description));titles.add(title);descriptions.add(description);assert.ok(html.includes(`<link rel="canonical" href="https://conversiontype.com/${slug}/">`));assert.ok(html.includes('application/ld+json'));assert.ok(sitemap.includes(`https://conversiontype.com/${slug}/`));if(slug==='date-time-calculators'){for(const child of slugs.slice(1))assert.ok(html.includes(`/${child}/`))}else{for(const required of['data-date-time-form','data-date-time-result','<h2>Examples</h2>','class="related-grid"','date-time.js'])assert.ok(html.includes(required),`${slug}: ${required}`)}}
assert.ok(!/<loc>[^<]*\?/.test(sitemap));assert.ok((await readFile('index.html','utf8')).includes('/date-time-calculators/'));assert.ok((await readFile('app.js','utf8')).includes("'business day'"));
console.log('Passed date/time calendar, duration, overnight, month-end, leap-year, business-day, age, DST-stability, SEO, sitemap, and internal-link checks.');
