import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import vm from'node:vm';
const source=await readFile(new URL('../unit-conversion.js',import.meta.url),'utf8');
for(const sharedName of['form','status','definitions'])assert.ok(!new RegExp(`const\\s+${sharedName}\\b|,${sharedName}=`).test(source),`converter global ${sharedName} must not collide with shared app globals`);
function page({key='cm',reverse=false,search=''}){const listeners={},from={value:'',labels:[{textContent:'From'}],addEventListener(n,f){listeners.from=f}},to={value:'',labels:[{textContent:'To'}],addEventListener(n,f){listeners.to=f}},form={dataset:{conversion:key,...(reverse?{reverse:'true'}:{})},elements:{from,to},addEventListener(n,f){listeners[n]=f}},share={textContent:'Share result',addEventListener(n,f){listeners.share=f}},status={textContent:'',dataset:{}},location={href:'https://conversiontype.com/test/'+search,search},history={replaceState(_a,_b,u){location.href=String(u);location.search=new URL(location.href).search}};let copied='';const document={title:'Converter',activeElement:from,querySelector(s){return s==='[data-conversion-form]'?form:s==='[data-share]'?share:s==='[data-conversion-status]'?status:null}};vm.runInNewContext(source,{document,location,history,navigator:{clipboard:{async writeText(v){copied=v}}},URL,URLSearchParams,Number,Math,Object});return{from,to,status,listeners,location,copied:()=>copied,document}}
const cases=[
 ['cm',false,'2.54','1'],['cm',true,'1','2.54'],['kg',false,'1','2.20462262185'],['kg',true,'2.20462262185','1'],
 ['km',false,'1.609344','1'],['km',true,'1','1.609344'],['feet',false,'1','0.3048'],['feet',true,'1','3.28083989501'],
 ['ounces',false,'1','28.349523125'],['ounces',true,'28.349523125','1'],['celsius',false,'0','32'],['celsius',true,'32','0'],['celsius',false,'-40','-40']
];
for(const[key,reverse,input,expected]of cases){const p=page({key,reverse});p.from.value=input;p.listeners.from();assert.equal(p.to.value,expected,`${key} ${reverse?'reverse page':'forward page'}`);assert.equal(new URL(p.location.href).searchParams.get('source'),'from');const restored=page({key,reverse,search:new URL(p.location.href).search});assert.equal(restored.from.value,input);assert.equal(restored.to.value,expected)}
for(const value of['0','0.000001','1.25','999999999']){const p=page({key:'cm'});p.from.value=value;p.listeners.from();assert.ok(p.to.value&&!p.to.value.includes('0000000000004'))}
const bidirectional=page({key:'cm'});bidirectional.to.value='1';bidirectional.listeners.to();assert.equal(bidirectional.from.value,'2.54');assert.equal(new URL(bidirectional.location.href).searchParams.get('source'),'to');await bidirectional.listeners.share();assert.equal(bidirectional.copied(),bidirectional.location.href);
const roundedTrip=page({key:'feet',reverse:true});roundedTrip.to.value='3.28083989501';roundedTrip.listeners.to();assert.equal(roundedTrip.from.value,'1');
for(const search of['?source=bad&value=1','?source=from&value=nope','?source=from','?value=2'])assert.match(page({search}).status.textContent,/invalid values/);
const slugs=['unit-converters','cm-to-inches','kg-to-lbs','inches-to-cm','lbs-to-kg','celsius-to-fahrenheit','fahrenheit-to-celsius','km-to-miles','miles-to-km','feet-to-meters','meters-to-feet','ounces-to-grams','grams-to-ounces'];
const sitemap=await readFile('sitemap.xml','utf8'),titles=new Set(),descriptions=new Set();
for(const slug of slugs){const html=await readFile(`${slug}/index.html`,'utf8');const title=html.match(/<title>([^<]+)/)?.[1],description=html.match(/<meta name="description" content="([^"]+)/)?.[1];assert.ok(title&&description&&html.includes(`<link rel="canonical" href="https://conversiontype.com/${slug}/">`));assert.ok(!titles.has(title)&&!descriptions.has(description));titles.add(title);descriptions.add(description);assert.ok(html.includes('application/ld+json'));assert.ok(sitemap.includes(`https://conversiontype.com/${slug}/`));if(slug!=='unit-converters'){for(const needle of['data-conversion-form','<h2>Formula</h2>','<h2>Examples</h2>','<table>','class="related-grid"','unit-conversion.js'])assert.ok(html.includes(needle),`${slug}: ${needle}`);assert.match(html,/conversion factor|Celsius and Fahrenheit scales/)}else for(const slug2 of slugs.slice(1))assert.ok(html.includes(`/${slug2}/`))}
assert.ok(!/<loc>[^<]*\?/.test(sitemap));
const forward=await readFile('cm-to-inches/index.html','utf8'),reverse=await readFile('inches-to-cm/index.html','utf8');assert.ok(forward.includes('inches = centimeters ÷ 2.54'));assert.ok(reverse.includes('centimeters = inches × 2.54'));assert.notEqual(forward,reverse);
console.log('Passed unit calculations, bidirectional conversion, precision, shared state, malformed state, SEO pages, tables, links, canonicals, and sitemap checks.');
