import{access,readFile}from'node:fs/promises';
import{percentageToRatio,ratioConversions,scaleRatio,simplifyRatio,solveProportion}from'../ratio-calculator/ratio-core.mjs';
const required=['index.html','styles.css','app.js','robots.txt','sitemap.xml','site.webmanifest','favicon.ico','favicon-16x16.png','favicon-32x32.png','apple-touch-icon.png','android-chrome-192x192.png','android-chrome-512x512.png','assets/conversiontype-logo.png','ratio-calculator/index.html','ratio-calculator/ratio.css','ratio-calculator/ratio.js','ratio-calculator/ratio-core.mjs','.github/workflows/release-gates.yml'];
await Promise.all(required.map(file=>access(file)));
const html=await readFile('index.html','utf8'),ratioHtml=await readFile('ratio-calculator/index.html','utf8'),ratioJs=await readFile('ratio-calculator/ratio.js','utf8'),manifest=JSON.parse(await readFile('site.webmanifest','utf8')),all=html+ratioHtml+ratioJs;
const equal=(actual,expected,name)=>{if(JSON.stringify(actual)!==JSON.stringify(expected))throw new Error(`Ratio test failed: ${name}; received ${JSON.stringify(actual)}`)};
equal(simplifyRatio(150,100),[3,2],'simplify 150:100');equal(simplifyRatio(1.5,1),[3,2],'decimal simplify');equal(solveProportion(['3','4','9','']).answer,12,'solve 3:4 = 9:x');equal(scaleRatio(2,3,10),[10,15],'scale 2:3 to 10');equal(ratioConversions(1,4).percentage,25,'ratio to percentage');equal(percentageToRatio(25),[1,4],'percentage to ratio');
const checks=[[html.includes('href="/ratio-calculator/"'),'homepage ratio link'],[ratioHtml.includes('<meta name="description"'),'ratio SEO description'],[ratioHtml.includes('Ratio Calculator'),'ratio title'],[ratioHtml.includes('Share result'),'share control'],[ratioHtml.includes('Advertisement</small><strong>Reserved space'),'reserved ad only'],[ratioHtml.includes('Frequently asked questions'),'search content'],[ratioJs.includes('navigator.share'),'Web Share support'],[all.includes('id="privacy"'),'privacy choices'],[!/(googletagmanager|doubleclick|adsbygoogle|google-analytics)/i.test(all),'no provider scripts'],[manifest.name==='ConversionType','web manifest']];
for(const[passed,name]of checks)if(!passed)throw new Error(`Release gate failed: ${name}`);console.log(`Passed ${checks.length} platform checks and 6 ratio math tests.`);
