import{test,expect}from'@playwright/test';
const routes=['/cups-to-ounces/','/ounces-to-cups/','/cups-to-tablespoons/','/tablespoons-to-cups/','/tablespoons-to-teaspoons/','/cups-to-ml/','/ml-to-cups/','/grams-to-cups/','/cups-to-grams/','/butter-converter/'];
async function dismiss(page){await page.waitForTimeout(450);const d=page.locator('#privacy');if(await d.count()&&await d.isVisible())await d.getByRole('button',{name:'Essential only'}).click()}
async function noOverflow(page){expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(()=>window.innerWidth))}
test('cooking hub and representative tools fit every viewport',async({page},testInfo)=>{for(const path of['/cooking-conversions/','/cups-to-ounces/','/grams-to-cups/','/butter-converter/']){await page.goto(path);await dismiss(page);await expect(page.locator('h1')).toBeVisible();await noOverflow(page);if(path!=='/cooking-conversions/'){await expect(page.locator('[name="from"]')).toBeVisible();await expect(page.locator('[name="to"]')).toBeVisible()}}await page.screenshot({path:testInfo.outputPath(`cooking-${testInfo.project.name}.png`),fullPage:true})});
test.describe('cooking calculator matrix at 320px',()=>{test.skip(({viewport})=>viewport?.width!==320,'matrix runs once');
 const cases=[['/cups-to-ounces/','1','8'],['/ounces-to-cups/','8','1'],['/cups-to-tablespoons/','1','16'],['/tablespoons-to-cups/','16','1'],['/tablespoons-to-teaspoons/','1','3'],['/cups-to-ml/','1','236.5882365'],['/ml-to-cups/','236.5882365','1'],['/grams-to-cups/','120','1'],['/cups-to-grams/','1','120']];
 for(const[path,input,answer]of cases)test(`${path} converts both ways and restores state`,async({page})=>{await page.goto(path);await dismiss(page);await page.locator('[name="from"]').fill(input);await expect(page.locator('[name="to"]')).toHaveValue(answer);expect(new URL(page.url()).searchParams.get('source')).toBe('from');await page.reload();await expect(page.locator('[name="from"]')).toHaveValue(input);await expect(page.locator('[name="to"]')).toHaveValue(answer);await page.locator('[name="to"]').fill(answer);await expect(page.locator('[name="from"]')).toHaveValue(input);await noOverflow(page)});
 test('metric cup standard changes milliliter conversion and restores',async({page})=>{await page.goto('/cups-to-ml/');await page.locator('[name="standard"]').selectOption('metric');await page.locator('[name="from"]').fill('1');await expect(page.locator('[name="to"]')).toHaveValue('250');await page.reload();await expect(page.locator('[name="standard"]')).toHaveValue('metric');await expect(page.locator('[name="to"]')).toHaveValue('250')});
 test('ingredient selection changes grams per cup and restores',async({page})=>{await page.goto('/cups-to-grams/');await page.locator('[name="ingredient"]').selectOption('sugar');await page.locator('[name="from"]').fill('1');await expect(page.locator('[name="to"]')).toHaveValue('198');await page.reload();await expect(page.locator('[name="ingredient"]')).toHaveValue('sugar');await expect(page.locator('[name="to"]')).toHaveValue('198')});
 test('butter converts sticks and grams and restores unit state',async({page})=>{await page.goto('/butter-converter/');await page.locator('[name="fromUnit"]').selectOption('sticks');await page.locator('[name="toUnit"]').selectOption('grams');await page.locator('[name="from"]').fill('2');await expect(page.locator('[name="to"]')).toHaveValue('226.796185');await page.reload();await expect(page.locator('[name="fromUnit"]')).toHaveValue('sticks');await expect(page.locator('[name="toUnit"]')).toHaveValue('grams');await expect(page.locator('[name="to"]')).toHaveValue('226.796185')});
 test('invalid shared state and long values stay safe',async({page})=>{await page.goto('/grams-to-cups/?source=from&value=120&ingredient=not-food');await expect(page.locator('[data-cooking-status]')).toContainText('invalid');await page.locator('[name="from"]').fill('999999999999');await expect(page.locator('[name="to"]')).toBeVisible();await noOverflow(page)});
});