import{test,expect}from'@playwright/test';
const routes=['/cm-to-inches/','/kg-to-lbs/','/inches-to-cm/','/lbs-to-kg/','/celsius-to-fahrenheit/','/fahrenheit-to-celsius/','/km-to-miles/','/miles-to-km/','/feet-to-meters/','/meters-to-feet/','/ounces-to-grams/','/grams-to-ounces/'];
async function dismiss(page){await page.waitForTimeout(450);const d=page.locator('#privacy');if(await d.isVisible())await d.getByRole('button',{name:'Essential only'}).click()}
async function noOverflow(page){expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(await page.evaluate(()=>window.innerWidth))}
test('unit hub and representative converter fit every viewport',async({page},testInfo)=>{for(const path of['/unit-converters/','/cm-to-inches/','/celsius-to-fahrenheit/']){await page.goto(path);await dismiss(page);await expect(page.locator('h1')).toBeVisible();await expect(page.locator('header nav')).toBeVisible();await noOverflow(page);if(path!=='/unit-converters/'){await expect(page.locator('[name="from"]')).toBeVisible();await expect(page.locator('[name="to"]')).toBeVisible();const table=page.locator('.table-wrap');await expect(table).toBeVisible();expect(await table.evaluate(e=>e.scrollWidth>=e.clientWidth)).toBe(true);const trigger=page.locator('.definition-term').first();await trigger.focus();await page.keyboard.press('Enter');await expect(page.locator('.definition-bubble')).toBeVisible();const box=await page.locator('.definition-bubble').boundingBox();expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(testInfo.project.use.viewport.width+1);await page.keyboard.press('Escape')} }await page.screenshot({path:testInfo.outputPath(`unit-${testInfo.project.name}.png`),fullPage:true})});
test.describe('unit calculator matrix at 320px',()=>{test.skip(({viewport})=>viewport?.width!==320,'matrix runs once');
 const cases=[['/cm-to-inches/','2.54','1'],['/kg-to-lbs/','1','2.20462262185'],['/inches-to-cm/','1','2.54'],['/lbs-to-kg/','1','0.45359237'],['/celsius-to-fahrenheit/','-40','-40'],['/fahrenheit-to-celsius/','32','0'],['/km-to-miles/','1.609344','1'],['/miles-to-km/','1','1.609344'],['/feet-to-meters/','1','0.3048'],['/meters-to-feet/','1','3.28083989501'],['/ounces-to-grams/','1','28.349523125'],['/grams-to-ounces/','28.349523125','1']];
 for(const[path,input,answer]of cases)test(`${path} converts both ways and restores state`,async({page})=>{await page.goto(path);await dismiss(page);await page.locator('[name="from"]').fill(input);await expect(page.locator('[name="to"]')).toHaveValue(answer);const url=page.url();expect(new URL(url).searchParams.get('source')).toBe('from');await page.reload();await expect(page.locator('[name="from"]')).toHaveValue(input);await expect(page.locator('[name="to"]')).toHaveValue(answer);await page.locator('[name="to"]').fill(answer);await expect(page.locator('[name="from"]')).toHaveValue(input);await noOverflow(page)});
 test('invalid shared state and long numbers stay safe',async({page})=>{await page.goto('/cm-to-inches/?source=bad&value=nope');await expect(page.locator('[data-conversion-status]')).toContainText('invalid');await page.locator('[name="from"]').fill('999999999999');await expect(page.locator('[name="to"]')).toBeVisible();await noOverflow(page)});
});
